name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: CI=false npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          if [[ $GITHUB_REF_NAME == "main" ]]; then
            vercel --prod --token $VERCEL_TOKEN --confirm --yes
          elif [[ $GITHUB_REF_NAME == "develop" ]]; then
            vercel --token $VERCEL_TOKEN --confirm --yes
          fi
